//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELEntities : DbContext
    {
        public ELEntities()
            : base("name=ELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_AcssesBook> Tbl_AcssesBook { get; set; }
        public virtual DbSet<Tbl_AcssesBookContorl> Tbl_AcssesBookContorl { get; set; }
        public virtual DbSet<Tbl_BaseRole> Tbl_BaseRole { get; set; }
        public virtual DbSet<Tbl_BaseRolesPermission> Tbl_BaseRolesPermission { get; set; }
        public virtual DbSet<Tbl_Book> Tbl_Book { get; set; }
        public virtual DbSet<Tbl_BookDetails> Tbl_BookDetails { get; set; }
        public virtual DbSet<Tbl_BookDetailsFeatures> Tbl_BookDetailsFeatures { get; set; }
        public virtual DbSet<Tbl_BookDetailsNavigator> Tbl_BookDetailsNavigator { get; set; }
        public virtual DbSet<Tbl_BookTag> Tbl_BookTag { get; set; }
        public virtual DbSet<Tbl_BookType> Tbl_BookType { get; set; }
        public virtual DbSet<Tbl_BookValidateRequest> Tbl_BookValidateRequest { get; set; }
        public virtual DbSet<Tbl_BookValidateRequestProcess> Tbl_BookValidateRequestProcess { get; set; }
        public virtual DbSet<Tbl_BookValidateRequestState> Tbl_BookValidateRequestState { get; set; }
        public virtual DbSet<Tbl_branch> Tbl_branch { get; set; }
        public virtual DbSet<Tbl_Files> Tbl_Files { get; set; }
        public virtual DbSet<Tbl_FileType> Tbl_FileType { get; set; }
        public virtual DbSet<Tbl_ForgetPassword> Tbl_ForgetPassword { get; set; }
        public virtual DbSet<Tbl_Group> Tbl_Group { get; set; }
        public virtual DbSet<Tbl_Language> Tbl_Language { get; set; }
        public virtual DbSet<Tbl_Library> Tbl_Library { get; set; }
        public virtual DbSet<Tbl_Login> Tbl_Login { get; set; }
        public virtual DbSet<Tbl_Notification> Tbl_Notification { get; set; }
        public virtual DbSet<Tbl_NotificationType> Tbl_NotificationType { get; set; }
        public virtual DbSet<Tbl_Permission> Tbl_Permission { get; set; }
        public virtual DbSet<Tbl_RegisterCode> Tbl_RegisterCode { get; set; }
        public virtual DbSet<Tbl_RequestKind> Tbl_RequestKind { get; set; }
        public virtual DbSet<Tbl_RequestType> Tbl_RequestType { get; set; }
        public virtual DbSet<Tbl_Setting> Tbl_Setting { get; set; }
        public virtual DbSet<Tbl_SpecialAcssesBook> Tbl_SpecialAcssesBook { get; set; }
        public virtual DbSet<Tbl_Tag> Tbl_Tag { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_UsersPermission> Tbl_UsersPermission { get; set; }
        public virtual DbSet<Tbl_Wishlist> Tbl_Wishlist { get; set; }
    }
}
