//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Book = new HashSet<Tbl_Book>();
            this.Tbl_BookValidateRequest = new HashSet<Tbl_BookValidateRequest>();
            this.Tbl_BookValidateRequest1 = new HashSet<Tbl_BookValidateRequest>();
            this.Tbl_Files = new HashSet<Tbl_Files>();
            this.Tbl_Login = new HashSet<Tbl_Login>();
            this.Tbl_Notification = new HashSet<Tbl_Notification>();
            this.Tbl_SpecialAcssesBook = new HashSet<Tbl_SpecialAcssesBook>();
            this.Tbl_UsersPermission = new HashSet<Tbl_UsersPermission>();
            this.Tbl_Wishlist = new HashSet<Tbl_Wishlist>();
        }
    
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Family { get; set; }
        public string User_Email { get; set; }
        public string User_Mobile { get; set; }
        public System.DateTime User_Date { get; set; }
        public Nullable<int> User_BranchID { get; set; }
        public bool User_SABAlloow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Book> Tbl_Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookValidateRequest> Tbl_BookValidateRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookValidateRequest> Tbl_BookValidateRequest1 { get; set; }
        public virtual Tbl_branch Tbl_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Files> Tbl_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Login> Tbl_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notification> Tbl_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SpecialAcssesBook> Tbl_SpecialAcssesBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UsersPermission> Tbl_UsersPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Wishlist> Tbl_Wishlist { get; set; }
    }
}
