//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notification
    {
        public int Notification_ID { get; set; }
        public int Notification_UserID { get; set; }
        public string Notification_Message { get; set; }
        public bool Notification_Read { get; set; }
        public int Notification_NotificationTypeID { get; set; }
    
        public virtual Tbl_NotificationType Tbl_NotificationType { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
