//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookAcsses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BookAcsses()
        {
            this.Tbl_Book = new HashSet<Tbl_Book>();
            this.Tbl_BookCustomAcsses = new HashSet<Tbl_BookCustomAcsses>();
        }
    
        public int BookAcsses_ID { get; set; }
        public bool BookAcsses_Guest { get; set; }
        public bool BookAcsses_Global { get; set; }
        public bool BookAcsses_Local { get; set; }
        public bool BookAcsses_Custom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Book> Tbl_Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookCustomAcsses> Tbl_BookCustomAcsses { get; set; }
    }
}
