//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookValidateRequestProcess
    {
        public int BVRP_ID { get; set; }
        public int BVRP_BVRID { get; set; }
        public int BVRP_StateID { get; set; }
        public string BVRP_Description { get; set; }
        public System.DateTime BVRP_Date { get; set; }
    
        public virtual Tbl_BookValidateRequest Tbl_BookValidateRequest { get; set; }
        public virtual Tbl_BookValidateRequestState Tbl_BookValidateRequestState { get; set; }
    }
}
