//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Login()
        {
            this.Tbl_ForgetPassword = new HashSet<Tbl_ForgetPassword>();
        }
    
        public int Login_ID { get; set; }
        public string Login_PasswordSalt { get; set; }
        public string Login_PasswordHush { get; set; }
        public Nullable<int> Login_UserID { get; set; }
        public string Login_UserName { get; set; }
        public bool Login_RegisterActive { get; set; }
        public int Login_RegisterID { get; set; }
        public int Login_BaseRoleID { get; set; }
        public bool Login_CustomRole { get; set; }
        public bool Login_UserActive { get; set; }
        public bool Login_ISDelete { get; set; }
    
        public virtual Tbl_BaseRole Tbl_BaseRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ForgetPassword> Tbl_ForgetPassword { get; set; }
        public virtual Tbl_RegisterCode Tbl_RegisterCode { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
