//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Setting
    {
        public int Setting_ID { get; set; }
        public string Setting_GlobalIP { get; set; }
        public string Setting_LocalIP { get; set; }
        public string Setting_Smtp { get; set; }
        public string Setting_Email { get; set; }
        public string Setting_Password { get; set; }
    }
}
