//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookValidateRequestState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BookValidateRequestState()
        {
            this.Tbl_BookValidateRequestProcess = new HashSet<Tbl_BookValidateRequestProcess>();
        }
    
        public int BVRS_ID { get; set; }
        public int BVRS_Name { get; set; }
        public bool BVRS_ValidateAnswerable { get; set; }
        public bool BVRS_ValidateAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookValidateRequestProcess> Tbl_BookValidateRequestProcess { get; set; }
    }
}
