//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookDetailsNavigator
    {
        public int BDN_ID { get; set; }
        public int BDN_BDFID { get; set; }
        public int BDN_BookTypeID { get; set; }
    
        public virtual Tbl_BookDetailsFeatures Tbl_BookDetailsFeatures { get; set; }
        public virtual Tbl_BookType Tbl_BookType { get; set; }
    }
}
