//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AcssesBook
    {
        public int AcssesBook_ID { get; set; }
        public int AcssesBook_ABCID { get; set; }
        public Nullable<int> AcssesBook_GroupID { get; set; }
    
        public virtual Tbl_AcssesBookContorl Tbl_AcssesBookContorl { get; set; }
        public virtual Tbl_Group Tbl_Group { get; set; }
    }
}
