//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BaseRolesPermission
    {
        public int BRP_ID { get; set; }
        public int BRP_BaseRoleID { get; set; }
        public int BRP_PermissionID { get; set; }
    
        public virtual Tbl_BaseRole Tbl_BaseRole { get; set; }
        public virtual Tbl_Permission Tbl_Permission { get; set; }
    }
}
