//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BookDetails()
        {
            this.Tbl_Book = new HashSet<Tbl_Book>();
        }
    
        public int BD_ID { get; set; }
        public string BD_Name { get; set; }
        public Nullable<bool> BD_DigitalVersionAvailable { get; set; }
        public Nullable<bool> BD_PhysicalVersionAvailable { get; set; }
        public Nullable<int> BD_LibraryID { get; set; }
        public Nullable<bool> BD_FileEnabel { get; set; }
        public Nullable<int> BD_FileCount { get; set; }
        public Nullable<int> BD_PageCount { get; set; }
        public string BD_Titel { get; set; }
        public string BD_WriterName { get; set; }
        public string BD_Language { get; set; }
        public string BD_Description { get; set; }
        public string BD_Abstract { get; set; }
        public Nullable<System.DateTime> BD_ReleaseDate { get; set; }
        public Nullable<int> BD_ReleaseCount { get; set; }
        public Nullable<int> BD_StudentID { get; set; }
        public Nullable<int> BD_MasterID { get; set; }
        public string BD_Publishers { get; set; }
        public string BD_ISBN { get; set; }
        public string BD_Subject { get; set; }
        public Nullable<int> BD_GroupID { get; set; }
        public Nullable<int> BD_BranchID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Book> Tbl_Book { get; set; }
        public virtual Tbl_branch Tbl_branch { get; set; }
        public virtual Tbl_Group Tbl_Group { get; set; }
        public virtual Tbl_Library Tbl_Library { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        public virtual Tbl_User Tbl_User1 { get; set; }
    }
}
