//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookCustomAcsses
    {
        public int BCA_ID { get; set; }
        public int BCA_BAID { get; set; }
        public int BCA_TypeID { get; set; }
        public Nullable<int> BCA_BaseRoleID { get; set; }
        public Nullable<int> BCA_GroupID { get; set; }
        public Nullable<int> BCA_BranchID { get; set; }
    
        public virtual Tbl_BaseRole Tbl_BaseRole { get; set; }
        public virtual Tbl_BookAcsses Tbl_BookAcsses { get; set; }
        public virtual Tbl_BooKCustomAcssesType Tbl_BooKCustomAcssesType { get; set; }
        public virtual Tbl_branch Tbl_branch { get; set; }
        public virtual Tbl_Group Tbl_Group { get; set; }
    }
}
