//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RequestType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_RequestType()
        {
            this.Tbl_BookValidateRequest = new HashSet<Tbl_BookValidateRequest>();
        }
    
        public int RequestType_ID { get; set; }
        public string RequestType_Name { get; set; }
        public string RequestType_Titel { get; set; }
        public int RequestType_RequestKindID { get; set; }
        public Nullable<int> RequestType_BookTypeID { get; set; }
    
        public virtual Tbl_BookType Tbl_BookType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookValidateRequest> Tbl_BookValidateRequest { get; set; }
        public virtual Tbl_RequestKind Tbl_RequestKind { get; set; }
    }
}
