//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookValidateRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BookValidateRequest()
        {
            this.Tbl_BookValidateRequestProcess = new HashSet<Tbl_BookValidateRequestProcess>();
        }
    
        public int BVR_ID { get; set; }
        public int BVR_ApplicantUserID { get; set; }
        public int BVR_AnswerableUserID { get; set; }
        public string BVR_Titel { get; set; }
        public bool BVR_Enabel { get; set; }
        public int BVR_RequestTypeID { get; set; }
        public Nullable<int> BVR_BookID { get; set; }
    
        public virtual Tbl_RequestType Tbl_RequestType { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        public virtual Tbl_User Tbl_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookValidateRequestProcess> Tbl_BookValidateRequestProcess { get; set; }
        public virtual Tbl_Book Tbl_Book { get; set; }
    }
}
