//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Library.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Files
    {
        public int File_ID { get; set; }
        public int File_Index { get; set; }
        public string File_Name { get; set; }
        public string File_Path { get; set; }
        public Nullable<int> File_FileTypeID { get; set; }
        public int File_BookID { get; set; }
        public int File_UserUploaderID { get; set; }
        public System.DateTime File_Date { get; set; }
        public Nullable<bool> File_DownloadAcssesLocalIP { get; set; }
        public Nullable<bool> File_DownloadAcssesGlobalIP { get; set; }
        public System.Guid File_FolderName { get; set; }
    
        public virtual Tbl_Book Tbl_Book { get; set; }
        public virtual Tbl_FileType Tbl_FileType { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
